name: Build

on:
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Debug Vars
        run: |
          echo "Registry: ${{ vars.DOCKER_REGISTRY }}"
          echo "Namespace: ${{ vars.DOCKER_NAMESPACE }}"
          echo "Image Name: ${{ vars.DOCKER_IMAGE_NAME }}"

      - name: login to docker
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: create image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}
          tags: 'latest'

      - name: build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: cleanup older images
        uses: actions/delete-package-versions@v5
        with:
          package-name: cwx-proxy # Name of the package to delete older versions from
          package-type: container
          min-versions-to-keep: 10
          delete-only-pre-release-versions: "true"
